### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by janjagusch** [conda-forge/prettier-feedstock#16]

**Comment by sleighsoft** [comment]
What would be required to add windows support?

**Comment by janjagusch** [comment]
> What would be required to add windows support?

i have opened a PR to add Windows support a while back but it's quite working yet.

https://github.com/conda-forge/prettier-feedstock/pull/17/files#

the relevant changes are in `bld.bat` and `meta.yaml`

one thing that definitely still has to be added is a separate test case for Windows, as `grep` doesn't exist there: https://github.com/conda-forge/prettier-feedstock/pull/17/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR27

feel free to give it a try and see if you can make it work, i'd appreciate some help here. :)
